# Generated by Django 3.1.4 on 2020-12-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibebeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='border_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='brand',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='image_large',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_small',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='title_color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
