# Generated by Django 3.1.4 on 2020-12-23 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=360)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('units_on_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('meal_type', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main Course'), ('Desert', 'Desert')], max_length=50)),
                ('food_type', models.CharField(choices=[('Seafood', 'Seafood'), ('Chicken', 'Chicken'), ('Veal', 'Veal'), ('Pork', 'Pork'), ('Fish', 'Fish'), ('Vegetables', 'Vegetables'), ('Cheese', 'Cheese'), ('Chocolate', 'Chocolate'), ('Fruits', 'Fruits')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MealPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(default='ttps://res.cloudinary.com/dariku/image/upload/v1607681887/events/user-photos/user-default.jpg')),
                ('is_default', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('meal', models.ManyToManyField(to='meals.Meal')),
            ],
        ),
    ]
