# Generated by Django 3.1.4 on 2020-12-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='meal',
            field=models.ManyToManyField(blank=True, to='meals.Meal'),
        ),
    ]
